### PR TITLE
better

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Also: Maybe don't run as root?

**Comment by jakeajames** [comment]
@Blu3DevGit The install.sh script doesn't work if you don't run with sudo, the fixes which have to be ran with sudo aren't necessary for everyone, just for some Macs

**Comment by jakeajames** [comment]
@Blu3DevGit And there's nothing wrong comparing with @"", nil doesn't make a single difference

**Comment by ghost** [comment]
Can you atleast add my alt?

**Comment by jakeajames** [comment]
Sorry why I have to?

**Comment by ghost** [comment]
I put it in the top... You said aka ********* so I fixed it.

**Comment by jakeajames** [comment]
@Blu3DevGit ah don't worry the mods are going to know that soon :) My friend is going to take care of you

**Comment by ghost** [comment]
They don't care... Ive been suspended from reddit already...

**Comment by ghost** [comment]
They probably know

**Pull request closed without merging**
